resources:
- role.yaml
- role_binding.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml
- metrics_service.yaml
# Comment the following lines if you want to disable
# metrics endpoint authentication and authorization.
- metrics_auth_role.yaml
- metrics_auth_role_binding.yaml
- metrics_reader_role.yaml
# Comment the following 2 lines if you don't wish for the internal cert-manager
# approver to approve all certmanager.step.sm CertificateRequests by default.
- cert_manager_controller_approver_clusterrole.yaml
- cert_manager_controller_approver_clusterrolebinding.yaml
